export const GET_FILES_ACTION = "GET_FILES_ACTION";
export const DELETE_FILES_ACTION = "DELETE_FILES_ACTION";
export const CHANGE_CURRENT_FOLDER_ACTION = "CHANGE_CURRENT_FOLDER";
export const GO_BACK_PATH_ACTION = "GO_BACK_PATH_ACTION";
export const SAVE_FILES_ACTION = "SAVE_FILES_ACTION";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";