export const DEFINE_USER = "DEFINE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_ALL_FILES = "GET_ALL_FILES"
export const DELETE_FILES = "DELETE_FILES"
export const CHANGE_CURRENT_FOLDER = "CHANGE_CURRENT_FOLDER"
export const GO_BACK_PATH = "GO_BACK_PATH"